AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS EdiRecyclingPointsApi API - edi.recycling.points.api::edi-recycling-points-api
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  EdiRecyclingPointsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: edi.recycling.points.api.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://environment-app/c1efecda12932b5eafec86d28730b174
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 900
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  EdiRecyclingPointsApiApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/recyclingPoints
    Export:
      Name: EdiRecyclingPointsApiApi
